server.port=8080
spring.application.name=Sos-Gateway-Server

# Output to a file named application.log.
logging.file.name=log/gateway_server.log
spring.main.banner-mode=off
logging.logback.rollingpolicy.clean-history-on-start=true
logging.pattern.console=

#spring.cloud.gateway.globalcors.add-to-simple-url-handler-mapping=true
#spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedOrigins=*
#spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedHeaders=*
#spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedMethods=*

#spring.main.web-application-type=reactive