server.port=8761
spring.application.name=Sos-Eureka-Server
#spring.cloud.config.uri=http://myMachine.domain.lan:8888

eureka.datacenter=Sos
eureka.environment=dev and test
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
#eureka.instance.hostname=myDomain.lan
eureka.instance.prefer-ip-address=true
#eureka.instance.status-page-url-path=${eureka.hostName}/info
#eureka.instance.health-check-url=${eureka.hostName}/health

# Output to a file named application.log.
logging.file.name=log/eureka_server.log
spring.main.banner-mode=off
logging.logback.rollingpolicy.clean-history-on-start=true
logging.pattern.console=
