spring.application.name=Sos-Authorization-Server
server.port=12701

spring.datasource.url=jdbc:postgresql://localhost:5432/users
spring.datasource.username=test
spring.datasource.password=test

# true - Spring creates and controls changes in the database structure, false - does not create
spring.jpa.generate-ddl=false
spring.jpa.show-sql=false
# Be sure to replace create with validate
spring.jpa.hibernate.ddl-auto=validate

#spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring.session.jdbc.initialize-schema=always
spring.session.store-type=jdbc
spring.session.jdbc.table-name=SPRING_SESSION

jwt.secret.access=GMeok96460aCZ1YpE/lgEDuTHA6/1AaK2HgS4YErSMEnF+D+eOUkfC0OR0K8TKoAHJqpvrsQDzyZenrm/n+xPg==
jwt.secret.refresh=icgCQtL3cAY6MQii0d9uJeZEzF+yCe80okNaPTmWIbtf1Hex11G72oX3VqhyDEoHu4e3BmlO01KNqx54cFfRNg==

# Output to a file named application.log.
logging.file.name=log/auth_server.log
spring.main.banner-mode=off
logging.logback.rollingpolicy.clean-history-on-start=true
logging.pattern.console=